import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "rw" | "fr";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.getQuote": "Get a Quote",
    // Home
    "home.welcome": "Welcome to Noble Spaces",
    "home.tagline": "Your Space, Our Passion",
    "home.heroDesc": "Premium interior design & furniture solutions crafted with precision, elegance, and a passion for perfection.",
    "home.learnMore": "Learn More",
    "home.categories": "Signature Categories",
    "home.categoriesDesc": "Explore our most popular design categories",
    "home.whatWeDo": "What We Do",
    "home.ourServices": "Our Services",
    "home.completeSolutions": "Complete Solutions",
    "home.servicesDesc": "From concept to completion, we offer a full range of interior and furniture services.",
    "home.testimonials": "Testimonials",
    "home.whatClientsSay": "What Our Clients Say",
    "home.ctaTitle": "Ready to Transform Your Space?",
    "home.ctaDesc": "Let's discuss your vision. Contact us today for a free consultation and personalized quote.",
    "home.contactUs": "Contact Us",
    "home.explore": "Explore",
    "home.kitchenDesigns": "Kitchen Designs",
    "home.officeInteriors": "Office Interiors",
    "home.customFurniture": "Custom Furniture",
    // About
    "about.title": "About Us",
    "about.getInTouch": "Get In Touch",
    // Contact
    "contact.getInTouch": "Get In Touch",
    "contact.title": "Contact Us",
    "contact.subtitle": "Ready to transform your space? Reach out and let's start the conversation.",
    "contact.info": "Contact Information",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.location": "Location",
    "contact.hours": "Working Hours",
    "contact.hoursValue": "Mon - Sat: 8AM - 6PM",
    "contact.sendMessage": "Send Us a Message",
    "contact.fullName": "Full Name",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Phone",
    "contact.serviceLabel": "Service Interested In",
    "contact.selectService": "Select a service",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us about your project...",
    "contact.send": "Send Message",
    "contact.sent": "Message Sent!",
    "contact.sentDesc": "We'll get back to you within 24 hours.",
    "contact.visitShowroom": "Visit our showroom for an in-person consultation",
    // Service page
    "service.ourServices": "Our Services",
    "service.aboutService": "About This Service",
    "service.keyFeatures": "Key Features",
    "service.howItWorks": "How It Works",
    "service.ourProcess": "Our Process",
    "service.portfolio": "Portfolio",
    "service.ourWork": "Our Work",
    "service.interested": "Interested in",
    "service.requestQuote": "Request a free quote and let our experts create the perfect solution for you.",
    "service.requestService": "Request Service",
    "service.exploreOther": "Explore Other Services",
    "service.availability": "Availability",
    "service.inStock": "In Stock",
    "service.customMade": "Custom Made",
    "service.inStockDesc": "Available for immediate delivery",
    "service.customMadeDesc": "Made to order — typically 2-4 weeks",
    "service.bookService": "Book This Service",
    // Booking
    "booking.title": "Book a Service",
    "booking.name": "Full Name",
    "booking.email": "Email",
    "booking.phone": "Phone",
    "booking.date": "Preferred Date",
    "booking.pickDate": "Pick a date",
    "booking.time": "Preferred Time",
    "booking.selectTime": "Select a time",
    "booking.notes": "Additional Notes",
    "booking.notesPlaceholder": "Any special requirements...",
    "booking.submit": "Book Now",
    "booking.success": "Booking Submitted!",
    "booking.successDesc": "We'll confirm your appointment within 24 hours.",
  },
  rw: {
    "nav.home": "Ahabanza",
    "nav.about": "Turi bande",
    "nav.services": "Serivisi",
    "nav.contact": "Twandikire",
    "nav.getQuote": "Saba Igiciro",
    "home.welcome": "Murakaza neza kuri Noble Spaces",
    "home.tagline": "Umwanya Wawe, Ishyaka Ryacu",
    "home.heroDesc": "Ibisubizo by'ubwubatsi n'ibikoresho by'inzu bikoranye ubuhanga, ubwiza, n'urukundo.",
    "home.learnMore": "Menya Byinshi",
    "home.categories": "Ubwoko Bw'ingenzi",
    "home.categoriesDesc": "Reba ubwoko bwacu bw'ibikoresho bikunzwe cyane",
    "home.whatWeDo": "Ibyo Dukora",
    "home.ourServices": "Serivisi Zacu",
    "home.completeSolutions": "Ibisubizo Byuzuye",
    "home.servicesDesc": "Kuva ku gitekerezo kugeza ku murangizo, dutanga serivisi zuzuye z'ubwubatsi n'ibikoresho.",
    "home.testimonials": "Ibitekerezo",
    "home.whatClientsSay": "Abakiriya Bacu Bavuga Iki",
    "home.ctaTitle": "Witeguye Guhindura Umwanya Wawe?",
    "home.ctaDesc": "Reka tuvuge ku icyerekezo cyawe. Twandikire uyu munsi kugira ngo ubone inama n'igiciro.",
    "home.contactUs": "Twandikire",
    "home.explore": "Reba",
    "home.kitchenDesigns": "Imiterere y'Ibicaniro",
    "home.officeInteriors": "Imbere mu Biro",
    "home.customFurniture": "Ibikoresho Bidasanzwe",
    "about.title": "Turi Bande",
    "about.getInTouch": "Twandikire",
    "contact.getInTouch": "Twandikire",
    "contact.title": "Twandikire",
    "contact.subtitle": "Witeguye guhindura umwanya wawe? Twandikire dutangire ikiganiro.",
    "contact.info": "Amakuru y'Itumanaho",
    "contact.phone": "Telefoni",
    "contact.email": "Imeyili",
    "contact.location": "Aho Duherereye",
    "contact.hours": "Amasaha y'Akazi",
    "contact.hoursValue": "Kuwa Mbere - Kuwa Gatandatu: 8AM - 6PM",
    "contact.sendMessage": "Ohereza Ubutumwa",
    "contact.fullName": "Amazina Yuzuye",
    "contact.emailLabel": "Imeyili",
    "contact.phoneLabel": "Telefoni",
    "contact.serviceLabel": "Serivisi Ukeneye",
    "contact.selectService": "Hitamo serivisi",
    "contact.message": "Ubutumwa",
    "contact.messagePlaceholder": "Tubwire ku mushinga wawe...",
    "contact.send": "Ohereza Ubutumwa",
    "contact.sent": "Ubutumwa Bwoherejwe!",
    "contact.sentDesc": "Tuzagusubiza mu masaha 24.",
    "contact.visitShowroom": "Sura ishoramari ryacu kugira ngo ubone inama",
    "service.ourServices": "Serivisi Zacu",
    "service.aboutService": "Kuri Iyi Serivisi",
    "service.keyFeatures": "Ibintu By'ingenzi",
    "service.howItWorks": "Uko Bikora",
    "service.ourProcess": "Inzira Yacu",
    "service.portfolio": "Imirimo Yacu",
    "service.ourWork": "Imirimo Yacu",
    "service.interested": "Ukeneye",
    "service.requestQuote": "Saba igiciro ku buntu kandi impuguke zacu zikukorere ibisubizo byiza.",
    "service.requestService": "Saba Serivisi",
    "service.exploreOther": "Reba Izindi Serivisi",
    "service.availability": "Kuboneka",
    "service.inStock": "Birahari",
    "service.customMade": "Bikorwa ku Mwanya",
    "service.inStockDesc": "Birashoboka kugeza kuri wowe vuba",
    "service.customMadeDesc": "Bikorwa ku cyifuzo — bisanzwe bifata ibyumweru 2-4",
    "service.bookService": "Tegura Iyi Serivisi",
    "booking.title": "Tegura Serivisi",
    "booking.name": "Amazina Yuzuye",
    "booking.email": "Imeyili",
    "booking.phone": "Telefoni",
    "booking.date": "Itariki Ukunda",
    "booking.pickDate": "Hitamo itariki",
    "booking.time": "Isaha Ukunda",
    "booking.selectTime": "Hitamo isaha",
    "booking.notes": "Ibindi Bitekerezo",
    "booking.notesPlaceholder": "Ibyo ukeneye by'umwihariko...",
    "booking.submit": "Tegura Nonaha",
    "booking.success": "Gutegura Byakunze!",
    "booking.successDesc": "Tuzakwemeza mu masaha 24.",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.about": "À Propos",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.getQuote": "Demander un Devis",
    "home.welcome": "Bienvenue chez Noble Spaces",
    "home.tagline": "Votre Espace, Notre Passion",
    "home.heroDesc": "Solutions premium de design d'intérieur et de mobilier, conçues avec précision, élégance et passion.",
    "home.learnMore": "En Savoir Plus",
    "home.categories": "Catégories Phares",
    "home.categoriesDesc": "Découvrez nos catégories de design les plus populaires",
    "home.whatWeDo": "Ce Que Nous Faisons",
    "home.ourServices": "Nos Services",
    "home.completeSolutions": "Solutions Complètes",
    "home.servicesDesc": "Du concept à la réalisation, nous offrons une gamme complète de services d'intérieur et de mobilier.",
    "home.testimonials": "Témoignages",
    "home.whatClientsSay": "Ce Que Disent Nos Clients",
    "home.ctaTitle": "Prêt à Transformer Votre Espace?",
    "home.ctaDesc": "Discutons de votre vision. Contactez-nous aujourd'hui pour une consultation gratuite et un devis personnalisé.",
    "home.contactUs": "Contactez-nous",
    "home.explore": "Explorer",
    "home.kitchenDesigns": "Designs de Cuisine",
    "home.officeInteriors": "Intérieurs de Bureau",
    "home.customFurniture": "Mobilier Sur Mesure",
    "about.title": "À Propos",
    "about.getInTouch": "Contactez-nous",
    "contact.getInTouch": "Contactez-nous",
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Prêt à transformer votre espace? Contactez-nous et commençons la conversation.",
    "contact.info": "Informations de Contact",
    "contact.phone": "Téléphone",
    "contact.email": "Email",
    "contact.location": "Localisation",
    "contact.hours": "Heures d'Ouverture",
    "contact.hoursValue": "Lun - Sam: 8h - 18h",
    "contact.sendMessage": "Envoyez-nous un Message",
    "contact.fullName": "Nom Complet",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Téléphone",
    "contact.serviceLabel": "Service Souhaité",
    "contact.selectService": "Sélectionnez un service",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Parlez-nous de votre projet...",
    "contact.send": "Envoyer le Message",
    "contact.sent": "Message Envoyé!",
    "contact.sentDesc": "Nous vous répondrons dans les 24 heures.",
    "contact.visitShowroom": "Visitez notre showroom pour une consultation en personne",
    "service.ourServices": "Nos Services",
    "service.aboutService": "À Propos de ce Service",
    "service.keyFeatures": "Caractéristiques Clés",
    "service.howItWorks": "Comment Ça Marche",
    "service.ourProcess": "Notre Processus",
    "service.portfolio": "Portfolio",
    "service.ourWork": "Nos Réalisations",
    "service.interested": "Intéressé par",
    "service.requestQuote": "Demandez un devis gratuit et laissez nos experts créer la solution parfaite pour vous.",
    "service.requestService": "Demander le Service",
    "service.exploreOther": "Découvrir d'Autres Services",
    "service.availability": "Disponibilité",
    "service.inStock": "En Stock",
    "service.customMade": "Sur Mesure",
    "service.inStockDesc": "Disponible pour livraison immédiate",
    "service.customMadeDesc": "Fabriqué sur commande — généralement 2 à 4 semaines",
    "service.bookService": "Réserver ce Service",
    "booking.title": "Réserver un Service",
    "booking.name": "Nom Complet",
    "booking.email": "Email",
    "booking.phone": "Téléphone",
    "booking.date": "Date Souhaitée",
    "booking.pickDate": "Choisir une date",
    "booking.time": "Heure Souhaitée",
    "booking.selectTime": "Choisir une heure",
    "booking.notes": "Notes Supplémentaires",
    "booking.notesPlaceholder": "Des exigences particulières...",
    "booking.submit": "Réserver Maintenant",
    "booking.success": "Réservation Soumise!",
    "booking.successDesc": "Nous confirmerons votre rendez-vous dans les 24 heures.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem("noble-lang");
    return (saved as Language) || "en";
  });

  const handleSetLang = (newLang: Language) => {
    setLang(newLang);
    localStorage.setItem("noble-lang", newLang);
  };

  const t = (key: string) => translations[lang][key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
