import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "rw" | "fr";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.getQuote": "Get a Quote",
    // Home
    "home.welcome": "Welcome to Noble Spaces",
    "home.tagline": "Your Space, Our Passion",
    "home.heroDesc": "Premium interior design & furniture solutions crafted with precision, elegance, and a passion for perfection.",
    "home.learnMore": "Learn More",
    "home.categories": "Signature Categories",
    "home.categoriesDesc": "Explore our most popular design categories",
    "home.whatWeDo": "What We Do",
    "home.ourServices": "Our Services",
    "home.completeSolutions": "Complete Solutions",
    "home.servicesDesc": "From concept to completion, we offer a full range of interior and furniture services.",
    "home.testimonials": "Testimonials",
    "home.whatClientsSay": "What Our Clients Say",
    "home.ctaTitle": "Ready to Transform Your Space?",
    "home.ctaDesc": "Let's discuss your vision. Contact us today for a free consultation and personalized quote.",
    "home.contactUs": "Contact Us",
    "home.explore": "Explore",
    "home.kitchenDesigns": "Kitchen Designs",
    "home.officeInteriors": "Office Interiors",
    "home.customFurniture": "Custom Furniture",
    // About
    "about.title": "About Us",
    "about.heading": "Our Story",
    "about.whoWeAre": "Who We Are",
    "about.craftingTitle": "Crafting Exceptional Spaces Since Day One",
    "about.story1": "Noble Spaces is a premier interior design and furniture company dedicated to transforming spaces into works of art. We combine creative vision with technical expertise to deliver solutions that exceed expectations.",
    "about.story2": "Our team of skilled designers, craftsmen, and project managers work collaboratively to bring your vision to life. From residential homes to commercial offices, we approach every project with the same level of dedication and attention to detail.",
    "about.workWithUs": "Work With Us",
    "about.missionLabel": "Our Mission",
    "about.missionTitle": "Delivering High-Quality Interior & Furniture Solutions",
    "about.missionDesc": "We are committed to creating spaces that inspire, comfort, and endure. Through craftsmanship, customization, and modern design, we transform your environment into something extraordinary.",
    "about.valuesLabel": "Our Values",
    "about.valuesTitle": "What Drives Us",
    "about.craftsmanship": "Craftsmanship",
    "about.craftsmanshipDesc": "Every project reflects meticulous attention to detail and superior quality.",
    "about.customization": "Customization",
    "about.customizationDesc": "Tailored solutions designed around your unique vision and lifestyle.",
    "about.modernDesign": "Modern Design",
    "about.modernDesignDesc": "Contemporary aesthetics that blend timeless elegance with innovation.",
    "about.clientFirst": "Client First",
    "about.clientFirstDesc": "Your satisfaction drives every decision we make.",
    "about.getInTouch": "Get In Touch",
    // Footer
    "footer.tagline": "Your Space, Our Passion",
    "footer.about": "Delivering high-quality interior design and furniture solutions with craftsmanship, customization, and modern design excellence.",
    "footer.services": "Services",
    "footer.moreServices": "More Services",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    // Portfolio
    "nav.portfolio": "Portfolio",
    "portfolio.label": "Our Work",
    "portfolio.title": "Projects & Transformations",
    "portfolio.subtitle": "Explore our completed projects with stunning before & after transformations.",
    "portfolio.before": "Before",
    "portfolio.after": "After",
    "portfolio.dragHint": "Drag the slider to compare",
    "portfolio.viewAll": "View All Projects",
    "portfolio.ctaTitle": "Ready to Start Your Transformation?",
    "portfolio.ctaDesc": "Let's create your next stunning space together.",
    // Contact
    "contact.getInTouch": "Get In Touch",
    "contact.title": "Contact Us",
    "contact.subtitle": "Ready to transform your space? Reach out and let's start the conversation.",
    "contact.info": "Contact Information",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.location": "Location",
    "contact.hours": "Working Hours",
    "contact.hoursValue": "Mon - Sat: 8AM - 6PM",
    "contact.sendMessage": "Send Us a Message",
    "contact.fullName": "Full Name",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Phone",
    "contact.serviceLabel": "Service Interested In",
    "contact.selectService": "Select a service",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us about your project...",
    "contact.send": "Send Message",
    "contact.sent": "Message Sent!",
    "contact.sentDesc": "We'll get back to you within 24 hours.",
    "contact.visitShowroom": "Visit our showroom for an in-person consultation",
    // Service page
    "service.ourServices": "Our Services",
    "service.aboutService": "About This Service",
    "service.keyFeatures": "Key Features",
    "service.howItWorks": "How It Works",
    "service.ourProcess": "Our Process",
    "service.portfolio": "Portfolio",
    "service.ourWork": "Our Work",
    "service.interested": "Interested in",
    "service.requestQuote": "Request a free quote and let our experts create the perfect solution for you.",
    "service.requestService": "Request Service",
    "service.exploreOther": "Explore Other Services",
    "service.availability": "Availability",
    "service.inStock": "In Stock",
    "service.customMade": "Custom Made",
    "service.inStockDesc": "Available for immediate delivery",
    "service.customMadeDesc": "Made to order — typically 2-4 weeks",
    "service.bookService": "Book This Service",
    // Booking
    "booking.title": "Book a Service",
    "booking.name": "Full Name",
    "booking.email": "Email",
    "booking.phone": "Phone",
    "booking.date": "Preferred Date",
    "booking.pickDate": "Pick a date",
    "booking.time": "Preferred Time",
    "booking.selectTime": "Select a time",
    "booking.notes": "Additional Notes",
    "booking.notesPlaceholder": "Any special requirements...",
    "booking.submit": "Book Now",
    "booking.success": "Booking Submitted!",
    "booking.successDesc": "We'll confirm your appointment within 24 hours.",
  },
  rw: {
    "nav.home": "Ahabanza",
    "nav.about": "Turi bande",
    "nav.services": "Serivisi",
    "nav.contact": "Twandikire",
    "nav.getQuote": "Saba Igiciro",
    "home.welcome": "Murakaza neza kuri Noble Spaces",
    "home.tagline": "Umwanya Wawe, Ishyaka Ryacu",
    "home.heroDesc": "Ibisubizo by'ubwubatsi n'ibikoresho by'inzu bikoranye ubuhanga, ubwiza, n'urukundo.",
    "home.learnMore": "Menya Byinshi",
    "home.categories": "Ubwoko Bw'ingenzi",
    "home.categoriesDesc": "Reba ubwoko bwacu bw'ibikoresho bikunzwe cyane",
    "home.whatWeDo": "Ibyo Dukora",
    "home.ourServices": "Serivisi Zacu",
    "home.completeSolutions": "Ibisubizo Byuzuye",
    "home.servicesDesc": "Kuva ku gitekerezo kugeza ku murangizo, dutanga serivisi zuzuye z'ubwubatsi n'ibikoresho.",
    "home.testimonials": "Ibitekerezo",
    "home.whatClientsSay": "Abakiriya Bacu Bavuga Iki",
    "home.ctaTitle": "Witeguye Guhindura Umwanya Wawe?",
    "home.ctaDesc": "Reka tuvuge ku icyerekezo cyawe. Twandikire uyu munsi kugira ngo ubone inama n'igiciro.",
    "home.contactUs": "Twandikire",
    "home.explore": "Reba",
    "home.kitchenDesigns": "Imiterere y'Ibicaniro",
    "home.officeInteriors": "Imbere mu Biro",
    "home.customFurniture": "Ibikoresho Bidasanzwe",
    "about.title": "Turi Bande",
    "about.heading": "Inkuru Yacu",
    "about.whoWeAre": "Turi Bande",
    "about.craftingTitle": "Dukora Imyanya Idasanzwe Kuva Umunsi wa Mbere",
    "about.story1": "Noble Spaces ni isosiyete ikomeye y'ubwubatsi n'ibikoresho by'inzu yiyemeje guhindura imyanya kuba ubuhanzi. Duhuriza hamwe icyerekezo cy'ubuhanga n'ubumenyi bwa tekiniki kugira ngo dutange ibisubizo birenze ibyitezwe.",
    "about.story2": "Itsinda ryacu ry'abadizayinari, abahanga, n'abayobozi b'imishinga bakorera hamwe kugira ngo bahindure icyerekezo cyawe cyo nyacyo. Kuva mu nzu zo gutuyemo kugeza mu biro by'ubucuruzi, dukora buri mushinga twitaye ku buryo bumwe.",
    "about.workWithUs": "Dukorere Hamwe",
    "about.missionLabel": "Intego Yacu",
    "about.missionTitle": "Gutanga Ibisubizo Byiza by'Ubwubatsi n'Ibikoresho",
    "about.missionTitle": "Gutanga Ibisubizo Byiza by'Ubwubatsi n'Ibikoresho",
    "about.missionDesc": "Twiyemeje gukora imyanya itera ishema, yoroheye, kandi irambye. Ku bwobuhanga, guhindurwa ku cyifuzo, n'ubudizayinari bushya, duhindura aho uri kuba ahantu hadasanzwe.",
    "about.valuesLabel": "Indangagaciro Zacu",
    "about.valuesTitle": "Icyo Dushakira",
    "about.craftsmanship": "Ubuhanga",
    "about.craftsmanshipDesc": "Buri mushinga ugaragaza ubwitange ku makuru no ku bwiza burenze.",
    "about.customization": "Guhindurwa ku Cyifuzo",
    "about.customizationDesc": "Ibisubizo byateguwe ku cyerekezo cyawe n'imibereho yawe.",
    "about.modernDesign": "Ubudizayinari Bushya",
    "about.modernDesignDesc": "Imiterere igezweho ihuza ubwiza n'udushya.",
    "about.clientFirst": "Umukiriya Mbere",
    "about.clientFirstDesc": "Ibyishimo byawe biyobora buri cyemezo dufata.",
    "about.getInTouch": "Twandikire",
    "footer.tagline": "Umwanya Wawe, Ishyaka Ryacu",
    "footer.about": "Gutanga ibisubizo byiza by'ubwubatsi n'ibikoresho by'inzu hifashishijwe ubuhanga, guhindurwa ku cyifuzo, n'ubudizayinari bushya.",
    "footer.services": "Serivisi",
    "footer.moreServices": "Izindi Serivisi",
    "footer.contact": "Twandikire",
    "footer.rights": "Uburenganzira bwose burabitswe.",
    "nav.portfolio": "Imirimo",
    "portfolio.label": "Imirimo Yacu",
    "portfolio.title": "Imishinga n'Impinduka",
    "portfolio.subtitle": "Reba imishinga twarangije n'impinduka zitangaje za mbere n'iz'inyuma.",
    "portfolio.before": "Mbere",
    "portfolio.after": "Nyuma",
    "portfolio.dragHint": "Kurura akamenyetso kugira ngo ugereranye",
    "portfolio.viewAll": "Reba Imishinga Yose",
    "portfolio.ctaTitle": "Witeguye Gutangira Impinduka Yawe?",
    "portfolio.ctaDesc": "Reka dushyireho hamwe umwanya wawe ukurikira utangaje.",
    "contact.getInTouch": "Twandikire",
    "contact.title": "Twandikire",
    "contact.subtitle": "Witeguye guhindura umwanya wawe? Twandikire dutangire ikiganiro.",
    "contact.info": "Amakuru y'Itumanaho",
    "contact.phone": "Telefoni",
    "contact.email": "Imeyili",
    "contact.location": "Aho Duherereye",
    "contact.hours": "Amasaha y'Akazi",
    "contact.hoursValue": "Kuwa Mbere - Kuwa Gatandatu: 8AM - 6PM",
    "contact.sendMessage": "Ohereza Ubutumwa",
    "contact.fullName": "Amazina Yuzuye",
    "contact.emailLabel": "Imeyili",
    "contact.phoneLabel": "Telefoni",
    "contact.serviceLabel": "Serivisi Ukeneye",
    "contact.selectService": "Hitamo serivisi",
    "contact.message": "Ubutumwa",
    "contact.messagePlaceholder": "Tubwire ku mushinga wawe...",
    "contact.send": "Ohereza Ubutumwa",
    "contact.sent": "Ubutumwa Bwoherejwe!",
    "contact.sentDesc": "Tuzagusubiza mu masaha 24.",
    "contact.visitShowroom": "Sura ishoramari ryacu kugira ngo ubone inama",
    "service.ourServices": "Serivisi Zacu",
    "service.aboutService": "Kuri Iyi Serivisi",
    "service.keyFeatures": "Ibintu By'ingenzi",
    "service.howItWorks": "Uko Bikora",
    "service.ourProcess": "Inzira Yacu",
    "service.portfolio": "Imirimo Yacu",
    "service.ourWork": "Imirimo Yacu",
    "service.interested": "Ukeneye",
    "service.requestQuote": "Saba igiciro ku buntu kandi impuguke zacu zikukorere ibisubizo byiza.",
    "service.requestService": "Saba Serivisi",
    "service.exploreOther": "Reba Izindi Serivisi",
    "service.availability": "Kuboneka",
    "service.inStock": "Birahari",
    "service.customMade": "Bikorwa ku Mwanya",
    "service.inStockDesc": "Birashoboka kugeza kuri wowe vuba",
    "service.customMadeDesc": "Bikorwa ku cyifuzo — bisanzwe bifata ibyumweru 2-4",
    "service.bookService": "Tegura Iyi Serivisi",
    "booking.title": "Tegura Serivisi",
    "booking.name": "Amazina Yuzuye",
    "booking.email": "Imeyili",
    "booking.phone": "Telefoni",
    "booking.date": "Itariki Ukunda",
    "booking.pickDate": "Hitamo itariki",
    "booking.time": "Isaha Ukunda",
    "booking.selectTime": "Hitamo isaha",
    "booking.notes": "Ibindi Bitekerezo",
    "booking.notesPlaceholder": "Ibyo ukeneye by'umwihariko...",
    "booking.submit": "Tegura Nonaha",
    "booking.success": "Gutegura Byakunze!",
    "booking.successDesc": "Tuzakwemeza mu masaha 24.",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.about": "À Propos",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.getQuote": "Demander un Devis",
    "home.welcome": "Bienvenue chez Noble Spaces",
    "home.tagline": "Votre Espace, Notre Passion",
    "home.heroDesc": "Solutions premium de design d'intérieur et de mobilier, conçues avec précision, élégance et passion.",
    "home.learnMore": "En Savoir Plus",
    "home.categories": "Catégories Phares",
    "home.categoriesDesc": "Découvrez nos catégories de design les plus populaires",
    "home.whatWeDo": "Ce Que Nous Faisons",
    "home.ourServices": "Nos Services",
    "home.completeSolutions": "Solutions Complètes",
    "home.servicesDesc": "Du concept à la réalisation, nous offrons une gamme complète de services d'intérieur et de mobilier.",
    "home.testimonials": "Témoignages",
    "home.whatClientsSay": "Ce Que Disent Nos Clients",
    "home.ctaTitle": "Prêt à Transformer Votre Espace?",
    "home.ctaDesc": "Discutons de votre vision. Contactez-nous aujourd'hui pour une consultation gratuite et un devis personnalisé.",
    "home.contactUs": "Contactez-nous",
    "home.explore": "Explorer",
    "home.kitchenDesigns": "Designs de Cuisine",
    "home.officeInteriors": "Intérieurs de Bureau",
    "home.customFurniture": "Mobilier Sur Mesure",
    "about.title": "À Propos",
    "about.heading": "Notre Histoire",
    "about.whoWeAre": "Qui Nous Sommes",
    "about.craftingTitle": "Créer des Espaces Exceptionnels Depuis le Premier Jour",
    "about.story1": "Noble Spaces est une entreprise de design d'intérieur et de mobilier de premier plan qui se consacre à transformer les espaces en œuvres d'art. Nous combinons vision créative et expertise technique pour offrir des solutions qui dépassent les attentes.",
    "about.story2": "Notre équipe de designers qualifiés, d'artisans et de chefs de projet travaille en collaboration pour donner vie à votre vision. Des maisons résidentielles aux bureaux commerciaux, nous abordons chaque projet avec le même niveau de dévouement et d'attention aux détails.",
    "about.workWithUs": "Travailler Avec Nous",
    "about.missionLabel": "Notre Mission",
    "about.missionTitle": "Offrir des Solutions d'Intérieur et de Mobilier de Haute Qualité",
    "about.missionDesc": "Nous nous engageons à créer des espaces qui inspirent, réconfortent et perdurent. Grâce à l'artisanat, à la personnalisation et au design moderne, nous transformons votre environnement en quelque chose d'extraordinaire.",
    "about.valuesLabel": "Nos Valeurs",
    "about.valuesTitle": "Ce Qui Nous Anime",
    "about.craftsmanship": "Artisanat",
    "about.craftsmanshipDesc": "Chaque projet reflète une attention méticuleuse aux détails et une qualité supérieure.",
    "about.customization": "Personnalisation",
    "about.customizationDesc": "Des solutions sur mesure conçues autour de votre vision et de votre style de vie.",
    "about.modernDesign": "Design Moderne",
    "about.modernDesignDesc": "Une esthétique contemporaine qui allie élégance intemporelle et innovation.",
    "about.clientFirst": "Le Client D'Abord",
    "about.clientFirstDesc": "Votre satisfaction guide chaque décision que nous prenons.",
    "about.getInTouch": "Contactez-nous",
    "footer.tagline": "Votre Espace, Notre Passion",
    "footer.about": "Offrir des solutions de design d'intérieur et de mobilier de haute qualité avec artisanat, personnalisation et excellence du design moderne.",
    "footer.services": "Services",
    "footer.moreServices": "Plus de Services",
    "footer.contact": "Contact",
    "footer.rights": "Tous droits réservés.",
    "nav.portfolio": "Portfolio",
    "portfolio.label": "Nos Réalisations",
    "portfolio.title": "Projets & Transformations",
    "portfolio.subtitle": "Découvrez nos projets achevés avec de superbes transformations avant/après.",
    "portfolio.before": "Avant",
    "portfolio.after": "Après",
    "portfolio.dragHint": "Faites glisser pour comparer",
    "portfolio.viewAll": "Voir Tous les Projets",
    "portfolio.ctaTitle": "Prêt à Commencer Votre Transformation?",
    "portfolio.ctaDesc": "Créons ensemble votre prochain espace époustouflant.",
    "contact.getInTouch": "Contactez-nous",
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Prêt à transformer votre espace? Contactez-nous et commençons la conversation.",
    "contact.info": "Informations de Contact",
    "contact.phone": "Téléphone",
    "contact.email": "Email",
    "contact.location": "Localisation",
    "contact.hours": "Heures d'Ouverture",
    "contact.hoursValue": "Lun - Sam: 8h - 18h",
    "contact.sendMessage": "Envoyez-nous un Message",
    "contact.fullName": "Nom Complet",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Téléphone",
    "contact.serviceLabel": "Service Souhaité",
    "contact.selectService": "Sélectionnez un service",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Parlez-nous de votre projet...",
    "contact.send": "Envoyer le Message",
    "contact.sent": "Message Envoyé!",
    "contact.sentDesc": "Nous vous répondrons dans les 24 heures.",
    "contact.visitShowroom": "Visitez notre showroom pour une consultation en personne",
    "service.ourServices": "Nos Services",
    "service.aboutService": "À Propos de ce Service",
    "service.keyFeatures": "Caractéristiques Clés",
    "service.howItWorks": "Comment Ça Marche",
    "service.ourProcess": "Notre Processus",
    "service.portfolio": "Portfolio",
    "service.ourWork": "Nos Réalisations",
    "service.interested": "Intéressé par",
    "service.requestQuote": "Demandez un devis gratuit et laissez nos experts créer la solution parfaite pour vous.",
    "service.requestService": "Demander le Service",
    "service.exploreOther": "Découvrir d'Autres Services",
    "service.availability": "Disponibilité",
    "service.inStock": "En Stock",
    "service.customMade": "Sur Mesure",
    "service.inStockDesc": "Disponible pour livraison immédiate",
    "service.customMadeDesc": "Fabriqué sur commande — généralement 2 à 4 semaines",
    "service.bookService": "Réserver ce Service",
    "booking.title": "Réserver un Service",
    "booking.name": "Nom Complet",
    "booking.email": "Email",
    "booking.phone": "Téléphone",
    "booking.date": "Date Souhaitée",
    "booking.pickDate": "Choisir une date",
    "booking.time": "Heure Souhaitée",
    "booking.selectTime": "Choisir une heure",
    "booking.notes": "Notes Supplémentaires",
    "booking.notesPlaceholder": "Des exigences particulières...",
    "booking.submit": "Réserver Maintenant",
    "booking.success": "Réservation Soumise!",
    "booking.successDesc": "Nous confirmerons votre rendez-vous dans les 24 heures.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem("noble-lang");
    return (saved as Language) || "en";
  });

  const handleSetLang = (newLang: Language) => {
    setLang(newLang);
    localStorage.setItem("noble-lang", newLang);
  };

  const t = (key: string) => translations[lang][key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
